### ISSUE TITLE
unix_timeは今後使う変数ですか？

### ISSUE THREAD

**Issue by taruscript** [taruscript/TsukushiSpeaker#4]
GUI.pyにて

```python
def format_image_to_dict(paths):
    images = collections.defaultdict(list)
    for path in paths:
        unix_time, date, name = path.split("-")
        name = name.rstrip(".jpg")
        images[name].append({"date":date, "img":img_to_b64(path).decode('utf-8')})
    return images
```

**Comment by allgemein** [comment]
いいえ，使いません……
アンパックする方法をあまり知らなかったので使わない変数を置いています。

**Comment by taruscript** [comment]
なるほどです

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @aGreenPolarBear, @newtonapple, @dyxcrazy, @cyrto, @izzetemredemir, @Ashu2k, @ztjshaha, @astra-a, @eliyastein, @zhgoh, @mariustache, @xiaojay, @kankunnawat, @rafael-abuawad, @whoerau, @mkmitchell, @senjinwang, @mickhagen, @mpdevilleres, @niseak, @LHerskind, @shimakaze-git, @martinku-tw, @BitJunky, @noev, @folkyatina, @cargonriv, @bshambaugh, @mx472756841, @soub4i, @len-cl, @h4gen, @vlad-bb, @somtomking, @oo7ww, @kombu-takana, @caentzminger, @JustinLee2018, @somerb, @1yping, @vakond, @andrewmahoneyf, @atlasstrategic, @liangxiao0315, @rentruewang, @BhavyaSheth22, @RiccardoBiffi, @muellerberndt, @jedsada-gh, @navidsalehi

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
